services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    command: server /data --address :9000
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: image-processor
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: